# Generated by Django 3.2.3 on 2021-05-28 16:45

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210528_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeradditional',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+880', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+880', max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name='selleradditional',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+880', max_length=128, region=None),
        ),
    ]
