# Generated by Django 3.2.3 on 2021-05-30 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('Seller', 'SELLER'), ('Customer', 'CUSTOMER')], default='Customer', max_length=255, verbose_name='Type'),
        ),
    ]
