# Generated by Django 3.2.3 on 2021-06-01 05:55

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210531_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='images',
            field=models.ImageField(blank=True, default='profile.jpeg', max_length=200, upload_to='customer_profile/images', verbose_name='profile_pic'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='profession',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Customer', 'CUSTOMER'), ('Seller', 'SELLER')], default=['CUSTOMER'], max_length=15, null=True),
        ),
    ]
