# Generated by Django 3.2.3 on 2021-06-01 06:14

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20210601_1155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='images',
        ),
        migrations.AddField(
            model_name='customeradditional',
            name='images',
            field=models.ImageField(blank=True, default='profile.jpeg', max_length=200, upload_to='customer_profile/images', verbose_name='profile_pic'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Customer', 'CUSTOMER'), ('Seller', 'SELLER')], default=[], max_length=15, null=True),
        ),
    ]
