# Generated by Django 3.2.3 on 2021-06-01 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210601_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeradditional',
            name='images',
            field=models.ImageField(blank=True, default='profile.jpg', max_length=200, upload_to='customer_profile/images', verbose_name='profile_pic'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, default='profile.jpg', max_length=200, upload_to='profile/images', verbose_name='profile_pic')),
                ('email_confirmed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-pk',),
            },
        ),
    ]
