# Generated by Django 3.2.3 on 2021-06-08 01:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_contact_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='date_added',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
