# Generated by Django 3.2.3 on 2021-06-20 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_contact_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Company_name',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='customuser',
            name='goodstype',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='customuser',
            name='warehouse_location',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
