# Generated by Django 3.2.3 on 2021-06-21 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productfeatures',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.RemoveField(
            model_name='sellerproduct',
            name='category',
        ),
        migrations.RemoveField(
            model_name='sellerproduct',
            name='parent',
        ),
        migrations.DeleteModel(
            name='ProductFacility',
        ),
        migrations.DeleteModel(
            name='ProductFeatures',
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
        migrations.DeleteModel(
            name='SellerProduct',
        ),
    ]
