# Generated by Django 3.2.3 on 2021-06-11 16:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=100)),
                ('offer_title', models.CharField(max_length=100)),
                ('banar_height', models.FloatField(blank=True, null=True)),
                ('banar_width', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, height_field='banar_height', upload_to='shop/product/banar', width_field='banar_width')),
                ('offer_spain', models.CharField(blank=True, max_length=100, null=True)),
                ('btn_title', models.CharField(blank=True, default='Shop Now', max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Banar_carnival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carnival_title', models.CharField(max_length=100)),
                ('carnival_offer_title', models.CharField(max_length=100)),
                ('banar_height', models.FloatField(blank=True, null=True)),
                ('banar_width', models.FloatField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, height_field='banar_height', upload_to='shop/product/banar', width_field='banar_width')),
            ],
        ),
        migrations.CreateModel(
            name='MyShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator])),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(default='+880-', max_length=128, region=None)),
                ('address', models.CharField(max_length=200)),
                ('country', models.CharField(default='Bangladesh', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Newsletter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, validators=[django.core.validators.EmailValidator])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('price', models.IntegerField(default=0)),
                ('currency', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('del_price', models.CharField(blank=True, max_length=50, null=True)),
                ('offers_price', models.CharField(blank=True, max_length=60, null=True)),
                ('product_type', models.CharField(blank=True, choices=[('New', 'New'), ('Latest', 'Latest')], max_length=70, null=True)),
                ('stock', models.IntegerField(blank=True, default=1, null=True)),
                ('description', models.TextField(verbose_name='description')),
                ('image', models.ImageField(blank=True, height_field='height', upload_to='shop/product/images', width_field='width')),
                ('num_visits', models.IntegerField(default=0)),
                ('last_visit', models.DateTimeField(blank=True, null=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=150, unique=True)),
                ('image', models.ImageField(blank=True, upload_to='shop/product/category/images')),
                ('is_featured', models.BooleanField(default=False)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='shop.subcategory')),
            ],
            options={
                'verbose_name_plural': 'Subcategories',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('stars', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='shop.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(height_field='height', upload_to='shop/product/images', width_field='width')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.TextField(blank=True, null=True, verbose_name='feature')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility', models.TextField(blank=True, null=True, verbose_name='facility')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='shop.subcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='shop.product'),
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deliverystatus', models.CharField(max_length=150)),
                ('quantity', models.IntegerField(default=1)),
                ('orderdate', models.DateTimeField(default=django.utils.timezone.now)),
                ('product_id', models.ManyToManyField(related_name='product', to='shop.Product')),
            ],
        ),
    ]
