# Generated by Django 3.2.3 on 2021-06-22 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_suplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='approve',
            field=models.BooleanField(default=False),
        ),
    ]
