# Generated by Django 3.2.3 on 2021-06-25 03:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_product_suplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productfacility',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product_facility', to='shop.product'),
        ),
        migrations.AlterField(
            model_name='productfeatures',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product_feature', to='shop.product'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='shop.product'),
        ),
    ]
