# Generated by Django 3.2.3 on 2021-06-26 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20210620_1310'),
        ('shop', '0006_auto_20210625_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='suplier',
            field=models.ForeignKey(default='admin@gmail.com', on_delete=django.db.models.deletion.CASCADE, related_name='products', to='users.seller'),
        ),
    ]
