# Generated by Django 3.2.3 on 2021-06-11 16:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0013_alter_contact_date_added'),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('address', models.CharField(blank=True, default='', max_length=250)),
                ('phone', models.CharField(blank=True, default='', max_length=50)),
                ('order_area', models.CharField(blank=True, default='', max_length=250)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('order_status', models.CharField(choices=[('cancel', 'cancel'), ('pending', 'pending'), ('recived', 'recived')], default='pending', max_length=20)),
                ('status', models.BooleanField(blank=True, default=False, null=True)),
                ('payment_status', models.CharField(blank=True, choices=[('cash_on_delivery', 'cash_on_delivery'), ('card', 'card')], default='cash_on_delivery', max_length=20, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
    ]
